"""
utils/models.py
---------------
Typed dataclasses and enums used as shared data contracts across all modules.
Using dataclasses avoids dict-key typos and makes IDE completion reliable.
"""

from __future__ import annotations

import datetime
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class Severity(str, Enum):
    """Nuclei / finding severity levels."""

    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"
    UNKNOWN = "unknown"

    @classmethod
    def from_string(cls, value: str) -> "Severity":
        try:
            return cls(value.lower())
        except ValueError:
            return cls.UNKNOWN

    @property
    def rank(self) -> int:
        """Numeric rank for sorting (higher = more severe)."""
        return {
            self.INFO: 0,
            self.LOW: 1,
            self.MEDIUM: 2,
            self.HIGH: 3,
            self.CRITICAL: 4,
            self.UNKNOWN: -1,
        }[self]


class ScanPhase(str, Enum):
    DISCOVERY = "discovery"
    PROBING = "probing"
    SCANNING = "scanning"
    REPORTING = "reporting"


class FindingType(str, Enum):
    SUBDOMAIN = "subdomain"
    LIVE_HOST = "live_host"
    PORT_SERVICE = "port_service"
    DIR_FILE = "dir_file"
    VULNERABILITY = "vulnerability"
    TECH_DETECTION = "tech_detection"
    WAF_DETECTION = "waf_detection"
    MANUAL_FLAG = "manual_flag"
    JS_SECRET = "js_secret"
    CLOUD_BUCKET = "cloud_bucket"
    HARVESTED_URL = "harvested_url"
    SCREENSHOT = "screenshot"


# ---------------------------------------------------------------------------
# Core dataclasses
# ---------------------------------------------------------------------------


@dataclass
class SubdomainRecord:
    """A discovered subdomain and its metadata."""

    domain: str
    source: str  # which tool/provider found it
    ip_addresses: List[str] = field(default_factory=list)
    cname: Optional[str] = None
    is_wildcard: bool = False
    dangling_cname: bool = False  # possible takeover indicator
    timestamp: datetime.datetime = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))


@dataclass
class LiveHost:
    """A probed live web service."""

    url: str
    status_code: int
    title: str = ""
    redirect_url: Optional[str] = None
    content_length: int = 0
    technologies: List[str] = field(default_factory=list)
    waf: Optional[str] = None
    headers: Dict[str, str] = field(default_factory=dict)
    server_banner: str = ""
    screenshot_path: Optional[str] = None   # populated by ScreenshotModule
    timestamp: datetime.datetime = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))


@dataclass
class PortService:
    """A discovered open port and service."""

    host: str
    port: int
    protocol: str = "tcp"
    service: str = ""
    version: str = ""
    banner: str = ""
    state: str = "open"
    timestamp: datetime.datetime = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))


@dataclass
class DirectoryFinding:
    """A discovered directory or file path."""

    url: str
    status_code: int
    content_length: int = 0
    redirect_url: str = ""
    source_tool: str = ""
    is_interesting: bool = False  # flagged for manual review
    timestamp: datetime.datetime = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))


@dataclass
class NucleiFinding:
    """A nuclei vulnerability/exposure finding."""

    template_id: str
    name: str
    severity: Severity
    host: str
    matched_at: str
    description: str = ""
    tags: List[str] = field(default_factory=list)
    reference: List[str] = field(default_factory=list)
    extracted_results: List[str] = field(default_factory=list)
    cvss_score: Optional[float] = None
    cve_ids: List[str] = field(default_factory=list)
    raw: str = ""
    timestamp: datetime.datetime = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))


@dataclass
class ManualFlag:
    """
    A finding that requires analyst-led manual validation.
    Generated by reporter to guide the human follow-up workflow.
    """

    flag_type: str          # e.g. "subdomain_takeover", "exposed_admin"
    target: str             # URL/host/service
    observation: str        # what was found
    significance: str       # why it matters
    evidence: str           # what data supports this
    raw_data_path: str      # where raw artifact is stored
    analyst_steps: List[str] = field(default_factory=list)
    auth_required: bool = False
    severity_hint: Severity = Severity.MEDIUM
    timestamp: datetime.datetime = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))


@dataclass
class SecretFinding:
    """A secret or credential extracted from a JavaScript file."""

    url: str           # JS file URL where the secret was found
    secret_type: str   # e.g. "AWS Access Key", "API Key", "JWT"
    secret_value: str  # The matched value (may be partially redacted)
    source_tool: str = "secretfinder"
    timestamp: datetime.datetime = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))


@dataclass
class CloudBucketFinding:
    """An open or misconfigured cloud storage bucket."""

    provider: str      # aws, gcp, azure, digitalocean, etc.
    bucket_name: str
    url: str
    is_public: bool = True
    finding_detail: str = ""
    source_tool: str = "cloudbucketscanner"
    timestamp: datetime.datetime = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))


@dataclass
class HarvestedURL:
    """A URL harvested from passive/active sources (gau, waybackurls, katana)."""

    url: str
    source: str        # gau | waybackurls | katana
    is_js: bool = False
    is_interesting: bool = False  # matches endpoint patterns
    timestamp: datetime.datetime = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))


@dataclass
class EvasionFinding:
    """A finding surfaced through WAF bypass / evasion techniques."""

    template_id: str
    matched_at: str
    name: str
    severity: str = "info"
    technique: str = ""        # e.g. "header-spoof", "nuclei-waf-bypass", "arjun"
    source_tool: str = ""
    raw: str = ""
    timestamp: datetime.datetime = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))


@dataclass
class ToolResult:
    """Captures the result of running an external tool."""

    tool_name: str
    target: str
    cmd: str
    return_code: int
    stdout: str
    stderr: str
    duration_seconds: float
    timed_out: bool = False
    raw_output_path: str = ""
    timestamp: datetime.datetime = field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))


@dataclass
class TargetContext:
    """Top-level container for a full scan session's results."""

    session_id: str
    targets: List[str]
    start_time: datetime.datetime
    end_time: Optional[datetime.datetime] = None
    subdomains: List[SubdomainRecord] = field(default_factory=list)
    live_hosts: List[LiveHost] = field(default_factory=list)
    port_services: List[PortService] = field(default_factory=list)
    directory_findings: List[DirectoryFinding] = field(default_factory=list)
    nuclei_findings: List[NucleiFinding] = field(default_factory=list)
    manual_flags: List[ManualFlag] = field(default_factory=list)
    tool_results: List[ToolResult] = field(default_factory=list)
    # --- Extended capability results ---
    harvested_urls: List[HarvestedURL] = field(default_factory=list)
    secret_findings: List[SecretFinding] = field(default_factory=list)
    cloud_bucket_findings: List[CloudBucketFinding] = field(default_factory=list)
    jwt_tokens: List[str] = field(default_factory=list)
    jwt_issues: List[Dict[str, Any]] = field(default_factory=list)
    ssti_findings: List[Dict[str, Any]] = field(default_factory=list)
    xxe_findings: List[Dict[str, Any]] = field(default_factory=list)
    deserialization_findings: List[Dict[str, Any]] = field(default_factory=list)
    path_traversal_findings: List[Dict[str, Any]] = field(default_factory=list)
    csrf_findings: List[Dict[str, Any]] = field(default_factory=list)
    race_condition_findings: List[Dict[str, Any]] = field(default_factory=list)
    oauth_findings: List[Dict[str, Any]] = field(default_factory=list)
    websocket_findings: List[Dict[str, Any]] = field(default_factory=list)
    cache_poisoning_findings: List[Dict[str, Any]] = field(default_factory=list)
    idor_findings: List[Dict[str, Any]] = field(default_factory=list)
    sqli_findings: List[Dict[str, Any]] = field(default_factory=list)
    xss_findings: List[Dict[str, Any]] = field(default_factory=list)
    open_redirects: List[Dict[str, Any]] = field(default_factory=list)
    ssrf_findings: List[Dict[str, Any]] = field(default_factory=list)
    cors_misconfigs: List[Dict[str, Any]] = field(default_factory=list)
    graphql_endpoints: List[str] = field(default_factory=list)
    info_disclosures: List[Dict[str, Any]] = field(default_factory=list)
    smuggling_findings: List[Dict[str, Any]] = field(default_factory=list)
    prototype_pollution: List[Dict[str, Any]] = field(default_factory=list)
    bypass_403_findings: List[Dict[str, Any]] = field(default_factory=list)
    hidden_params: List[Dict[str, Any]] = field(default_factory=list)
    api_schema_findings: List[Dict[str, Any]] = field(default_factory=list)
    mass_assignment_findings: List[Dict[str, Any]] = field(default_factory=list)
    dast_findings: List[Dict[str, Any]] = field(default_factory=list)
    sensitive_paths: List[Dict[str, Any]] = field(default_factory=list)
    auth_token: Optional[str] = None
    # --- WAF detection & evasion results ---
    waf_detections: Dict[str, str] = field(default_factory=dict)   # url → waf_name
    evasion_findings: List[EvasionFinding] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)

    @property
    def duration(self) -> Optional[datetime.timedelta]:
        if self.end_time:
            return self.end_time - self.start_time
        return None

    @property
    def domain(self) -> str:
        return self.targets[0] if self.targets else "target"

    @domain.setter
    def domain(self, value: str) -> None:
        if self.targets:
            self.targets[0] = value
        else:
            self.targets = [value]

    @property
    def cloud_buckets(self) -> List[CloudBucketFinding]:
        return self.cloud_bucket_findings

    @cloud_buckets.setter
    def cloud_buckets(self, value: List[CloudBucketFinding]) -> None:
        self.cloud_bucket_findings = value


ScanSession = TargetContext
